name: Deploy Proyecto Semestral - RASTREADOR

on:
  push:
    branches: [ "main" ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout del código
      uses: actions/checkout@v3

    - name: Revelar mapa de carpetas real
      run: |
        echo "=================================================="
        echo "1. ¿QUÉ HAY EN LA RAÍZ DEL REPOSITORIO?"
        echo "=================================================="
        ls -la
        
        echo ""
        echo "=================================================="
        echo "2. BUSCANDO ARCHIVOS POM.XML EN TODO EL PROYECTO"
        echo "=================================================="
        find . -name "pom.xml"
        
        echo ""
        echo "=================================================="
        echo "3. BUSCANDO ARCHIVOS DOCKERFILE EN TODO EL PROYECTO"
        echo "=================================================="
        find . -name "*Dockerfile*"
